Repository moderneinc/springboot-migration-workshop, pull requests merged in 2023-09, with the labels that each got.

#17 Add migrate your own project module
  docs/migrate-your-own-project/README.md
  docs/migrate-your-own-project/assets/support-timelines.png
  src/pages/index.md
Labels: enhancement

#18 Recipe development doc
  docs/recipe-development/README.md
  src/pages/index.md
Labels: enhancement

#19 some new cli changes
  docs/moderne-cli/README.md
  docs/moderne-cli/assets/mod-cli.png
Labels: bug

#21 some improvements and fixes
  docs/moderne-cli/README.md
  docs/moderne-cli/assets/mod-cli.png
Labels: documentation
